name: Tests de Régression

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]
  workflow_dispatch: # Permet d'exécuter manuellement

env:
  NODE_ENV: test
  CI: true

jobs:
  regression-tests:
    name: Tests E2E et Analyse de Régression
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: tchopmygrinds_test
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: tchopmygrinds_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: 📦 Checkout du code
      uses: actions/checkout@v4

    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: 🔧 Installation des dépendances
      run: |
        npm ci
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: 💎 Setup Ruby pour Rails
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true

    - name: 🗄️ Configuration de la base de données
      env:
        DATABASE_URL: postgresql://tchopmygrinds_test:testpassword@localhost:5432/tchopmygrinds_test
        RAILS_ENV: test
      run: |
        bundle exec rails db:create
        bundle exec rails db:migrate
        bundle exec rails db:seed

    - name: 🏗️ Build du frontend
      run: |
        npm run build:css
        npm run build:react

    - name: 🚀 Démarrage des serveurs (background)
      env:
        DATABASE_URL: postgresql://tchopmygrinds_test:testpassword@localhost:5432/tchopmygrinds_test
        RAILS_ENV: test
      run: |
        # Démarrer Rails en arrière-plan
        bundle exec rails server -p 3000 -e test &
        RAILS_PID=$!
        echo "RAILS_PID=$RAILS_PID" >> $GITHUB_ENV
        
        # Démarrer le serveur frontend en arrière-plan  
        npm run preview -- --port 3001 &
        FRONTEND_PID=$!
        echo "FRONTEND_PID=$FRONTEND_PID" >> $GITHUB_ENV
        
        # Attendre que les serveurs démarrent
        sleep 30
        
        # Vérifier que les serveurs répondent
        curl -f http://localhost:3000/api/v1/commerces || exit 1
        curl -f http://localhost:3001 || exit 1

    - name: 🧪 Exécution des tests de régression
      id: tests
      run: |
        npm run test:ci
      continue-on-error: true

    - name: 📊 Upload des artefacts de test
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-artifacts
        path: |
          test-artifacts/
          tests/reports/
          tests/screenshots/
        retention-days: 30

    - name: 📝 Commentaire PR avec les résultats
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = './test-artifacts/pr-report.md';
          
          if (fs.existsSync(path)) {
            const report = fs.readFileSync(path, 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
          }

    - name: 🔍 Vérification des régressions critiques
      if: always()
      run: |
        if [ -f "test-artifacts/ci-summary.json" ]; then
          RECOMMENDATION=$(cat test-artifacts/ci-summary.json | jq -r '.recommendation')
          echo "Recommandation: $RECOMMENDATION"
          
          if [ "$RECOMMENDATION" = "BLOCK" ]; then
            echo "🚨 DÉPLOIEMENT BLOQUÉ - Régressions critiques détectées"
            exit 1
          elif [ "$RECOMMENDATION" = "CAUTION" ]; then
            echo "⚠️ DÉPLOIEMENT AVEC PRUDENCE - Régressions mineures détectées"
            # Ne pas échouer, mais avertir
          else
            echo "✅ DÉPLOIEMENT AUTORISÉ - Aucune régression critique"
          fi
        else
          echo "❌ Impossible de lire le rapport de tests"
          exit 1
        fi

    - name: 🧹 Nettoyage
      if: always()
      run: |
        # Arrêter les serveurs
        if [ ! -z "$RAILS_PID" ]; then
          kill $RAILS_PID || true
        fi
        if [ ! -z "$FRONTEND_PID" ]; then
          kill $FRONTEND_PID || true
        fi